### ISSUE TITLE
iCloud not supported anymore?

### ISSUE THREAD

**Issue by doonot** [smarcet/CalDAVClient#17]
Hi @smarcet 

We are experiencing some issues since some days with iCloud. Whenever we try to authenticate a user with the following code, an exception is thrown. It was working before and we didn't change anything. Maybe Apple did?

```
public static function auth($username, $password, $user_id, $calendar_id) {
        self::$client = null;
        self::$nearestServer = null;

        self::$client = new CalDavClient(
            'https://p01-caldav.icloud.com:443',
            $username,
            $password
        );

        self::$calendarId = $calendar_id;
        self::$calendarHome = self::getCalendarHome();

        return self::$client->isValidServer();
    }
```

Throws this error: 
`CalDAVClient\Facade\Exceptions\UserUnAuthorizedException: in /Applications/MAMP/htdocs/calenso/vendor/smarcet/caldavclient/src/Facade/CalDavClient.php on line 182`

Do you have any idea why this could happen? We are using the app-specific-passwords that can be generated by Apple.

Thanks for your feedback.

Cheers
Patrick

**Comment by smarcet** [comment]
Hello, well i dont know which is the implementation of your code like the content of method getCalendarHome

but i could tell you that i am using this

```
   $client = new CalDavClient(
                CALDAV_BASE_SERVER_URL,
                $user,
                $app_password
            );

            $principals = $client->getUserPrincipal();

            $responses  = $principals->getResponses();

            foreach ($responses as $res) {
                $user_ppal_url = $res->getPrincipalUrl();
                break;
            }

            $res = $client->isValidServer();
```

and seems to be working fine

regards

**Comment by doonot** [comment]
The implementation of getCalendarHome() is the same as yours. The problem is that it really behaves randomly. Sometimes it works, then I get a 400 Bad Request response, then 403 Forbidden, and then it works again.

Could this problem be caused by instantiating the client for too many times?

**Comment by smarcet** [comment]
issue its fixed on commit https://github.com/smarcet/CalDAVClient/commit/5895f1ac543eb605f0bc2aee4fc0c7a9788eb944

cheers
