### ISSUE TITLE
Not able to get calendar home

### ISSUE THREAD

**Issue by doonot** [smarcet/CalDAVClient#8]
Hi there

I am currently trying to get events from iCloud to my application. Since some month I am having issues getting the calendars from iCloud (maybe they changed something on their side). So I wanted to try out this lib. However, it seems to be failing on the same code:
```
        self::$client = new CalDavClient(
            'https://p56-caldav.icloud.com/',
            'pxxxxxxxxxxxxx@gmail.com',
            'yxxx-xxxx-xxxx-xxxx'
        );

        // this is true
        $valid = self::$client->isValidServer();

        // get principal returns a valid url
        $res = self::$client->getUserPrincipal();
        $principal_url = $res->getPrincipalUrl();
       
       // here it fails: 
       $calendar_home = self::$client->getCalendarHome($principal_url);

```

A `NotFoundResourceException` is thrown. Are you guys able to get your calendar home? Any idea why it does not work for me? (tried a dozen of iCloud accounts now).

**Comment by smarcet** [comment]
i reviewed the code
and ran this test testCalendarHomes (https://github.com/smarcet/CalDAVClient/blob/master/tests/FacadeTest.php#L57)

using as $server_url this value "https://p01-caldav.icloud.com:443" and ran ok, i always use as default server that, and then get nearest one from CalendarHomesResponse::getRealCalDAVHost

also tested with your setting https://p56-caldav.icloud.com/ and got the forementioned exception
but then tried with https://p56-caldav.icloud.com ( without the final /) and worked like a charm
regards
