### ISSUE TITLE
Getting events results in "500 Internal Server Error"

### ISSUE THREAD

**Issue by doonot** [smarcet/CalDAVClient#9]
Thank you very much for your support on my last issue. I am now trying to receive events from a calendar, but it always results in an error. Here is my code:

```
$res = self::$client->getUserPrincipal();
$principal_url = $res->getPrincipalUrl();
$calendar_home = self::$client->getCalendarHome($principal_url);
$calendar_home_url = $calendar_home->getCalendarHomeSetUrl();

$start = new \DateTime('-1 week');
$end = new \DateTime('+ 1 week');

$filter = new CalendarQueryFilter(true, false, $start, $end);

// this produces this url: https://p56-caldav.icloud.com/2xxxxx427/calendars/F398F1E6-xxxx-4BEF-A15D-BBF5B5BB8537
$events = self::$client->getEventsByQuery($calendar_home_url . self::$calendar_id, $filter);
```

Error:
```
GuzzleHttp/Exception/ServerException
Server error: `REPORT https://p56-caldav.icloud.com/2xxxxx427/calendars/F398F1E6-xxxx-4BEF-A15D-BBF5B5BB8537` resulted in a `500 Internal Server Error` response
```

Am I doing something wrong here? The client is correctly initialized and valid.

Thank you very much for your support, I will give something back to you once this works.

**Comment by smarcet** [comment]
ok there was an issue with the code, basically to and from params were switched please get the latest version from dev-master and test it again, should be working now

regards
